### ISSUE TITLE
languageId is javascript but path icon show javascriptreact

### ISSUE THREAD

**Issue by tjx666** [ionutvmi/path-autocomplete#100]
@ionutvmi
I config the `.jsx` files the language to `javascript`, but the path suggestion list icon still javascriptreact.

![image](https://user-images.githubusercontent.com/41773861/143774466-a77245b6-a1a4-4c04-a2f2-d057284c1b3d.png)

![image](https://user-images.githubusercontent.com/41773861/143774400-7e300320-68ae-4a2f-8f63-cb89c6b6f339.png)

**Comment by ionutvmi** [comment]
The icon is not controlled by the autocomplete extension.
We only configure if the suggestion is a file or a folder.

You may want to use an extension like https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons to customize the icons.

It has more options to fine tune the displayed icons:
https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by tjx666** [comment]
I create an issue to vscode https://github.com/microsoft/vscode/issues/138250#issuecomment-983674440

**Comment by tjx666** [comment]
I had fix it in my fork. just set completionItem.detail to real file path. @ionutvmi

**Comment by ionutvmi** [comment]
Feel free to open a PR with the fix.

I can merge it and publiah it.

**Comment by tjx666** [comment]
I have change a lot in my fork, with many other optimize and publish my own version. You can have look at my fork https://github.com/tjx666/path-autocomplete/commits/master. You have two choice:
 1. If you would like to merge it, I would stop publish my own version and help maintain your version.
 2. You can just add `completion.detail = file.path;` to `PathAutocompleteProvider.ts` at line `49`

**Comment by ionutvmi** [comment]
hi @tjx666 ,

In general, I am in favor of modernizing the codebase and adding new features to the extension.

I reviewed the changes on the fork and they look ok to me.

I don't have too much time allocated to open source these days but I am also happy to add you as a contributor directly to this repo if you want to maintain these and future changes directly here.

**Comment by tjx666** [comment]
@ionutvmi I have made a pr
