### ISSUE TITLE
suggest path mappings

### ISSUE THREAD

**Issue by sfeldkamp** [ionutvmi/path-autocomplete#103]
I have path mappings for the following aliases setup.

```
"path-autocomplete.pathMappings": {
	"/": ...
	"/resources": ...
},
```

Is there anyway to be suggested "/resources" when I type "/"?  This would be in addition to the contents of the "/" folder.  I would prefer to have the mappings have a higher precedence for suggestion.

**Comment by tjx666** [comment]
try:

```json
"path-autocomplete.pathMappings": {
        "/": "/"
},
```

**Comment by ionutvmi** [comment]
please reopen if you still encounter issues
