### ISSUE TITLE
Incorrect omit file name extensions and duplicate intelligence

### ISSUE THREAD

**Issue by Mirrorgo** [ionutvmi/path-autocomplete#105]
Problem1: 
![image](https://user-images.githubusercontent.com/55936306/156474500-2b149d46-19d0-498e-9fb2-c4b197759e4f.png)
when I use path-autocomplete in a typescript project, the extension will show .tess files, but when I type my "Tab", the file name extensions will be omitted so that the editor will consider it as a .js file rather than a .less file.
![image](https://user-images.githubusercontent.com/55936306/156474520-01896d15-2252-4caf-bd96-d5cc720feaa9.png)

Problem2:
In the first picture above, main and main.tsx are the same file. How can I eliminate one of them?

**Comment by tjx666** [comment]
First Problem: 

try set in settings.json: 

```
"path-autocomplete.extensionOnImport": true,
```

**Comment by tjx666** [comment]
For second problem, you may nake an issue to VSCode.
Because this problem is happen recently, no problem before.

**Comment by tjx666** [comment]
@ionutvmi 
We should just ignore `.ts/.tsx/.js/.jsx` file suggest items when current line contains `import` or `require` ? The VSCode builtin supports `import ts/js` modules.

We may should provide an option to ignore suggest items like: `path-autocomplete.ignoreSuggestItemPath: "*.{ts|tsx|js|jsx}"`?

**Comment by Mirrorgo** [comment]
> @ionutvmi We should just ignore `.ts/.tsx/.js/.jsx` file suggest items when current line contains `import` or `require` ? The VSCode builtin supports `import ts/js` modules.
> 
> We may should provide an option to ignore suggest items like: `path-autocomplete.ignoreSuggestItemPath: "*.{ts|tsx|js|jsx}"`?
another extension in vscode called "Path Intellisense" support an option like this 👇Maybe you can imitate it.
![image](https://user-images.githubusercontent.com/55936306/156872269-a49cf4a7-2f8d-47de-a357-8c65fdd10b76.png)

**Comment by tjx666** [comment]
Those two setting is VSCode builtin settings. You can just set it to ignore builin typescript module path suggestion.

**Comment by tjx666** [comment]
@Mirrorgo
Another way to fix second problem is set:

```
"path-autocomplete.excludedItems": {
        "**/*.+(ts|tsx)": { "when": "**/*.+(ts|tsx)", "context": "import|require" }
}
```
