### ISSUE TITLE
Doesn't seem to work for the latest version of VS Code

### ISSUE THREAD

**Issue by istudiomobile** [ionutvmi/path-autocomplete#11]
Installed but nothing happens as start to write path. Latest version of VS Code.

**Comment by ionutvmi** [comment]
Can you please provide more information about your environment ?
vscode version, OS

Please keep in mind that the autocomplete only works inside quotes.
Example: `<a href="./data/"`

**Comment by ionutvmi** [comment]
closing this as no feedback was received.

**Comment by alexpusch** [comment]
Doesn't work for me to. Simple require('./...') doesn't give any suggestions

 VS code version 1.12.2, Ubuntu 17.04

**Comment by ionutvmi** [comment]
I got an ubuntu VM and I was able to reproduce the issue.
It was caused by a file that got the wrong name during the publish process.
The issue should be fixed in 1.5.1

Please let me know if you still have issues.

**Comment by fbaiodias** [comment]
Hey @ionutvmi! Local path completion isn't working for me on OSX 10.12.5, VS Code 1.13.0, Path Autocomplete 1.5.1. `node_modules` completion seems to work fine though.
