### ISSUE TITLE
Auto recognize to use Slash or Backslash.

### ISSUE THREAD

**Issue by byehack** [ionutvmi/path-autocomplete#112]
![image](https://user-images.githubusercontent.com/26390254/187529967-425a9158-938b-439e-a8f6-37653b747138.png)

after Enter:

![image](https://user-images.githubusercontent.com/26390254/187530122-5b309d20-cbcc-4dd1-8dae-a9527aa1dc5e.png)

I Expected to have `x = "C:\Go\"` as result.

**Comment by ionutvmi** [comment]
if you work mainly with windows paths you can enable the `path-autocomplete.useBackslash` preference

auto-detecting is a good idea, I will keep this open until implemented

**Comment by byehack** [comment]
is this work for single backslash?

**Comment by ionutvmi** [comment]
this has been fixed in v1.21.0
Please try it out and reopen if you notice any issues.

**Comment by byehack** [comment]
> Please try it out and reopen if you notice any issues.

I don't have access to reopen this issue.
here is few issues:


https://user-images.githubusercontent.com/26390254/188280360-2f1e3dcf-3ca6-4ebf-beb1-dd810a9c3bc5.mp4
