### ISSUE TITLE
Don't overwrite double backslash

### ISSUE THREAD

**Issue by byehack** [ionutvmi/path-autocomplete#115]
![image](https://user-images.githubusercontent.com/26390254/188280920-8d4fe367-3ad0-4b4c-898d-64d9f6b46524.png)

after press enter:

![image](https://user-images.githubusercontent.com/26390254/188280941-fbf401fc-3bca-4a3d-b3ab-69a58b16307a.png)

Exprected: `"C:\Windows\"`

**Comment by ionutvmi** [comment]
At the moment this is the expected behavior inside quotes.

We keep single backslashes in inside raw strings
```
r"C:\Windows"
```

If you want this behavior all the time you can enable the `path-autocomplete.useSingleBackslash` preference.
