### ISSUE TITLE
File extension trimming

### ISSUE THREAD

**Issue by tomrobertsuk** [ionutvmi/path-autocomplete#12]
Is it possible to include the file extension when selecting a file? It's being trimmed currently. Is that the intended behavior?

**Comment by teamsteamdev** [comment]
Add this line to `settings.json`:

`"path-autocomplete.extensionOnImport": true`

This can be found under __Options__ in the documentation.

It would be nice if we could choose by file language (ie, `true` for `html`, `false` for `js`, etc).

**Comment by ionutvmi** [comment]
> It would be nice if we could choose by file language (ie, true for html, false for js, etc).

@teamsteamdev you should be able to do that with transformations
something like
```
"path-autocomplete.transformations": [{
    "type": "replace",
    "parameters": ["\\.html$", ""],
    "when": {
        "fileName": "\\.html$"
    }
}],
```
