### ISSUE TITLE
Better support for node_modules autocomplete

### ISSUE THREAD

**Issue by wszydlak** [ionutvmi/path-autocomplete#15]
In case when You have node_modules directory in your workspace autocomplete works perfectly, but, eg. when You have structure like that:

```
|-- index.js
|-- client
|   |-- node_modules
|   |   |-- react
|   |   |   |-- lib
|   |-- src
|   |  |-- client.js
|-- server
|   |-- node_modules
|   |   |-- express
|   |   |   |-- lib
|   |  |-- server.js
```

and You want to import **express/lib/something.js** in Your *server.js* file it doesnt work

import request from 'express/**lib/request**' -> it doesnt autocomplete bolded chars cause it cannot find express in workspace node_modules, cause node_modules in workspace root doesn't exists.

It will be cool if autocomplete for node_modules will lookup for closest parent node_modules directory and find module, and if not exists then lookup for next parent and so on.

**Comment by ionutvmi** [comment]
this should be available in 1.5.0
