### ISSUE TITLE
enable auto completion from package.json

### ISSUE THREAD

**Issue by vajahath** [ionutvmi/path-autocomplete#16]
let say my package.json got the following lines
```js
...
"dependencies": {
		"current-version": "vajahath/current-version",
		"lme": "^1.5.3",
		"semver-compare": "^1.0.0"
	}
}
...
```
So while I type:
```js
const compare = require("sem|")
//                          ^ -- cursor
```
it should autocomplete to `semver-compare`.

**Comment by ionutvmi** [comment]
This modules is meant to provide support with building paths and not intellisense for loading modules.
In your case it will provide support if you type something like `require("semver-compare/")`

For your needs you may want to use an extension like this on https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense

**Comment by vajahath** [comment]
Awesome :star:
