### ISSUE TITLE
Does not work with absolute path resolved by webpack

### ISSUE THREAD

**Issue by duwalanise** [ionutvmi/path-autocomplete#17]
I have a configuration in webpack shown below to resolve path
```
resolve: {
    modules: [
      path.resolve(`./react`),
      path.resolve('./node_modules'),
    ],
  },
```
I was expecting it to show all the folders and files inside resolved path

lets say i have folder `component` in side `react` so

`import  comp from 'component/'

should show list of files inside `component`.

**Comment by ionutvmi** [comment]
Have you tried using the mappings configurations `path-autocomplete.pathMappings` ?
You could say something like
```
"path-autocomplete.pathMappings": {
    "component": "${workspace}/node_modules/...../components"
}
```

**Comment by Pharylon** [comment]
I just came to look for the same issue!

My directory structure looks (in part) like this:
```
node_modules/
src/
├── assets/
├── scripts/
├── styles/
├── app.js
jsonconfig.json
webpack.config.js
```

So my webpack.config.js looks (in part) like this:

```
resolve: {
            modules: [
                path.resolve('./src'),
                path.resolve('./node_modules')
            ],
            extensions: ['.js']
        },
```

And in my jsconfig.json for Visual Studio Code, I have this:

```
//This file allows Visual Studio Code to supply useful intellisense. Not used for anything else.
{
    "compilerOptions": {
        "target": "ES6"
    },
    "include": [
        "src/**/*"
    ],
    "baseUrl": [
        "src"
    ]
}
```

So both Webpack and Visual Studio Code know that "src" is my source root. And the following will give me intellisense and (more importantly) compile with Webpack.

![pathintellisense](https://user-images.githubusercontent.com/2326271/27299918-e83276d0-54fb-11e7-884d-fdef05cfad96.png)

But path intellisense doesn't work. I was able to follow your suggestion and work around it with the following:

```
    "path-autocomplete.pathMappings": {
      "scripts": "${workspace}/src/scripts",
      "assets": "${workspace}/src/assets",
      "styles": "${workspace}/src/styles"
  }
```

But a more elegant solution would be if it respected the jsconfig.json file and used that to determine the path root.

**Comment by doque** [comment]
Setting the root path to `src` as described in the tutorial does not work for me.

My directory structure looks like this:

```
.
├── README.md
├── package.json
├── public
│   ├── favicon.ico
│   ├── index.html
│   └── manifest.json
├── src
│   ├── __mocks__
│   ├── actions
│   ├── assets
│   ├── components
│   ├── containers
│   ├── index.js
│   ├── reducers
│   ├── registerServiceWorker.js
│   ├── styles.css
│   └── util
└── yarn.lock
```
I've added this to my `settings.json`:
```
"path-autocomplete.pathMappings": {
    "/": "${workspace}/src"
  },
```
Unfortunately I'm not getting any suggestions relative to `/` when typing an `import`:

![image](https://user-images.githubusercontent.com/1480751/27644645-6015b890-5c24-11e7-8929-a371dc5e33d4.png)

**Comment by doque** [comment]
I found a solution by manually specifing all to-be-completed paths:

```
  "path-autocomplete.pathMappings": {
    "actions": "${workspace}/src/actions",
    "components": "${workspace}/src/components",
    "util": "${workspace}/src/util",
    "containers": "${workspace}/src/containers",
    "__mocks__": "${workspace}/src/__mocks__"
  }
```

**Comment by ionutvmi** [comment]
Closing this as `pathMappings` are currently the recommended solution.
