### ISSUE TITLE
package.json absolute path trick

### ISSUE THREAD

**Issue by Noitidart** [ionutvmi/path-autocomplete#18]
If we include a package.json we are able to use absolute paths. It would be so awesome if this extension was able to do intelli sense for that! Here is an article that explains the package.json absolute path trick - https://medium.com/@davidjwoody/how-to-use-absolute-paths-in-react-native-6b06ae3f65d1

**Comment by ionutvmi** [comment]
You should be able to do this today with pathMappings

```
"path-autocomplete.pathMappings": {
    "app": "${workspace}/src/app", // alias for app
}
```

but yes, it would be nice to detect the package.json automatically in the future.

**Comment by Noitidart** [comment]
Thanks @ionutvmi for your comment! :)

**Comment by ionutvmi** [comment]
I had a look over this and I decided that `pathMappings` is sufficient to enable this functionality,
