### ISSUE TITLE
Not working with npm intellisense

### ISSUE THREAD

**Issue by Noitidart** [ionutvmi/path-autocomplete#19]
I use NPM intellisense to fill in the package name when I open a quote - https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense
 
However once I do that, the npm path autocomplete doesn't work. (the feature from here - [https://github.com/ionutvmi/path-autocomplete/issues/16](https://github.com/ionutvmi/path-autocomplete/issues/16))

**Comment by ionutvmi** [comment]
I tried to reproduce this issue but it seems to work fine for me.
I get completion items from both extensions.

Can you provide more details ?

**Comment by Noitidart** [comment]
Oh maybe it's because I'm on a Mac. I uploaded a screencast here please:

https://youtu.be/rIvxyP1k9SU

**Comment by bjornhanson** [comment]
I'm also having an issue using this alongside the `npm Intellisense` extension. If only have one or the other enabled then the enabled extension works, but with both enabled this extension doesn't resolve paths in my `require` statements...only node modules show up.

**Comment by ionutvmi** [comment]
The fix should be available in 1.6.1
