### ISSUE TITLE
Option to turn off trailing slash for directories

### ISSUE THREAD

**Issue by Noitidart** [ionutvmi/path-autocomplete#20]
Every time, when I leave off on a directory, I never need the trailing slash. May you please disable this by default, or add an option for it?

I just made the move from Path Intellisense to this extension, and it is so great, thank you for it!

**Comment by ionutvmi** [comment]
We can add an option for this, I will have a look over it in the weekend.

**Comment by Noitidart** [comment]
Thanks so very much sir! I am making the move from PathIntellisense extension to yours and am absolutely loving it!!

**Comment by ionutvmi** [comment]
Added `path-autocomplete.enableFolderTrailingSlash`

**Comment by Noitidart** [comment]
Thank you sir!!
