### ISSUE TITLE
Extension is not included on autocomplete

### ISSUE THREAD

**Issue by Noitidart** [ionutvmi/path-autocomplete#21]
For non-js files we want the extension included on hitting tab.

Like resource is image.png, typing `import './i` then hitting tab only gives `import './image'`.

**Comment by ionutvmi** [comment]
For this kind of tasks you can use `path-autocomplete.transformations`.

Here is an example for removing the extension for scss files that start with _

```
"path-autocomplete.transformations": [{
    "type": "replace",
    "parameters": ["^_", ""],
    "when": {
        "fileName": "\\.scss$"
    }
}],
```

you can find more information in the readme file.

**Comment by Noitidart** [comment]
Thanks for that example @ionutvmi  !

**Comment by Noitidart** [comment]
Thanks for that example @ionutvmi ! I couldn't get it to work though, I want to not omit the extension, i want to include it if it is not a .js file.

**Comment by ionutvmi** [comment]
@Noitidart yes, my pattern was not removing the extension but `_` at the beginning of the file.
I have corrected the comment.

What you did is correct.

**Comment by Noitidart** [comment]
Thank you sir!
