### ISSUE TITLE
path start with '@' cause problem

### ISSUE THREAD

**Issue by zack24q** [ionutvmi/path-autocomplete#24]
first, my config is :
```
  "path-autocomplete.pathMappings": {
    "views": "${workspace}/src/views",
  }
```
![2017-09-21 19 04 04](https://user-images.githubusercontent.com/9154859/30692905-f286b832-9eff-11e7-9074-a500114765ae.gif)
every thing  works fine

but if i want add a `@` to `views` :
```
  "path-autocomplete.pathMappings": {
    "@views": "${workspace}/src/views",
  }
```
![2017-09-21 19 04 37](https://user-images.githubusercontent.com/9154859/30693039-717a68d2-9f00-11e7-9be2-65bc3ba113ec.gif)
`@views` cause problem, but single `@` works fine

![2017-09-21 19 13 24](https://user-images.githubusercontent.com/9154859/30693185-0211c6a6-9f01-11e7-96da-136c6c219d3d.gif)

need help

**Comment by cannap** [comment]
same! windows 10

**Comment by ionutvmi** [comment]
Hi @zack24q , @cannap ,

Can you try with something like this ?

```
    "@views/": "${workspace}/src/views",
```

Notice the additional / in there.

**Comment by ionutvmi** [comment]
Actually the `/` has nothing to do with it.

I'm not able to reproduce the issue on my local win 10.
Maybe you have another extension installed that causes some conflicts ?

I know there were some issues when running this with npm intellisesnse installed as well.

**Comment by ionutvmi** [comment]
Hi @zack24q , @cannap ,

Are you still experiencing this issue ?

**Comment by cannap** [comment]
@ionutvmi  for me it works now   or  "@": "${workspaceRoot}"  i changed to workspaceRoot

**Comment by ionutvmi** [comment]
Closing this with the assumption that it was fixed.

If you still have issues please reopen it.

**Comment by yoyoys** [comment]
@ionutvmi I've installed `npm-intellisense`, and set mapping like:
```
"path-intellisense.mappings": {
    "@/": "${workspaceRoot}/src/"
  },
```
works in `.vue` file, but `.js` file always find `node_modules` first.
