### ISSUE TITLE
path autocomplte extentions problem

### ISSUE THREAD

**Issue by dharmaraobalaga** [ionutvmi/path-autocomplete#25]
.jpg, .js, .css......like file extensions are not showing. so that file not working in preview
![vs code](https://user-images.githubusercontent.com/29701356/30852939-f6bb78ba-a2ca-11e7-8e99-197aeccc5072.jpg)

**Comment by BroFox86** [comment]
The same issue.

**Comment by ionutvmi** [comment]
Have you tried to set `path-autocomplete.extensionOnImport` to true in the settings ?
You can read more about the available settings in the readme.

**Comment by ionutvmi** [comment]
Closing this.

Assuming it was fixed.
