### ISSUE TITLE
add option for resolving absolute paths to the disk root path rather than the current workspace root path

### ISSUE THREAD

**Issue by dongzhuoer** [ionutvmi/path-autocomplete#26]
Could you please add a option like `"path-intellisense.absolutePathToWorkspace": false`

It will be very convenient for some users, especially those using Linux.

**Comment by gitzhuoer** [comment]
Sorry to disrupt you.

I find I can do it by

```json
"path-autocomplete.pathMappings": {
        "/": "/"     // the root folder is now GNU filesystem root directory
    }
```
