### ISSUE TITLE
Losing module intellisense when mapping paths

### ISSUE THREAD

**Issue by Gywem** [ionutvmi/path-autocomplete#28]
Hello everyone! First, thanks for this extension, very useful!

I tried to use the `pathMappings` on a project setting it up the next way:

This is my project structure
```
root/
  external-project/
    index.js
    module.js
  vs-project/
```

vseditor opens the `vs-project` and the user setting for `pathMappings` is configured as follows:
```
{
"path-autocomplete.pathMappings": {
    "root": "${home}/root"
  }
}
```

As expected, when I try to import a module, the path is autocompleted and I see the `external-project` reference and its content. I was able to autocomplete the next import:
```
import {} from 'root/external-project';
```

However, when I try to get the intellisense of the modules defined inside the `index.js` file of the `external-project` module, it doesn't work.

The thing is if I use relative paths, it works and I am able to see the module list of the `index.js` file and import `module`. 
```
import { module } from '../external-project';
```

So, is something wrong when specifying the path mappings? I cannot get the benefit of using alias for paths and don't lose the module intellisense (autocompletion, go to definition, etc).

**Comment by ionutvmi** [comment]
Hi,

The pathMappings is a configuration specific to this extension.
The intellisense from vs-code doesn't know about it and as a result it doesn't recognize the root/external-project path.

My recommendation would be to investigate if it's possible to configure a similar path mapping for the intellisense plugin.

I am closing this issue as it is not related to path completion.
