### ISSUE TITLE
Omits file extensions

### ISSUE THREAD

**Issue by timobure** [ionutvmi/path-autocomplete#31]
The autocomplete is very good but it omits file extensions.
For example:
`<link rel="stylesheet" href="/css/styles">`
`<script src="/node_modules/mdbootstrap/js/mdb.min"></script>`

instead of:
`<link rel="stylesheet" href="/css/styles.css">`
`<script src="/node_modules/mdbootstrap/js/mdb.min.js"></script>`

**Comment by timobure** [comment]
Sorry, I realized it's a setting option. Though getting to the options is a big hurdle

**Comment by ionutvmi** [comment]
Hi @timobure ,

The options are listed in the readme file.
Do you think we can change something to make them more clear ?
