### ISSUE TITLE
Is there a variable like {folder} for multi-folder workspace?

### ISSUE THREAD

**Issue by theodorDiaconu** [ionutvmi/path-autocomplete#32]
I need to add some mappings. Currently I have:
```
	"path-autocomplete.pathMappings": {
		"core": "${workspace}/core",
	},
```

So I have at workspace level a /core folder. But I also need some mappings that are folder specific. Do I need something like "${folder}/imports" ?

**Comment by theodorDiaconu** [comment]
I also notice that if I have mapping set-up, I cannot navigate to that certain file, like I can with relative import paths. Is this something this package should do ?

**Comment by theodorDiaconu** [comment]
After even more testing I realized that these `pathMappings` work only in the Workspace settings. If I remove it from there and have them in `Folder Settings`.


Tried this:
```
    "path-autocomplete.pathMappings": {
        "core": "${workspace}/core",
        "/": "${workspace}/microservices/app/",
    },
```

And this:
```
    "path-autocomplete.pathMappings": {
        "core": "${workspace}/imports/core", 
    },
```
^ Thinking that now ${workspace} is actually the folder root, and made a symlink to core.

**Comment by ionutvmi** [comment]
The `${folder}` variable was added in 1.8.0 

Please try it out and let me know if this works as expected for you.

**Comment by ionutvmi** [comment]
Closing this under the assumption that the issue was fixed.

If you still encounter issue please feel free to reopen it.

**Comment by theodorDiaconu** [comment]
I tried it, it works fine, thank you very much!

Regards,
Theodor
