### ISSUE TITLE
it doesn't work with brackets

### ISSUE THREAD

**Issue by alpgul** [ionutvmi/path-autocomplete#33]

**Comment by ionutvmi** [comment]
Hi @alpgul ,

Can you provide an example here ?

**Comment by alpgul** [comment]
[`](https://raw.githubusercontent.com/alpgul/Markdown-Example/master/issue.png)

**Comment by ionutvmi** [comment]
Try to enable the preference : `path-autocomplete.triggerOutsideStrings`

The autocomplete should be triggered when you press `/`

**Comment by Vxider** [comment]
Have the same problem. but add `path-autocomplete.triggerOutsideStrings` to the preference does not solve my problem, in markdown type `![](./)` cannot trigger path auto complete

**Comment by ionutvmi** [comment]
This issue should be fixed in 1.8.1

Please let me know if you still encounter issues with it.
