### ISSUE TITLE
Automatically list folders/files after autocompletion of folder

### ISSUE THREAD

**Issue by westr029** [ionutvmi/path-autocomplete#34]
Thanks for making this extension available. It works really great.
The only thing I am missing is that I need to type a backslash everytime I excepted an autocompletion of a folder.

I would prefer that after I pressed Enter to choose a folder to autocomplete, that immediately after that a new list is popping up showing a list of files/folders in that accepted folder.

I hope it is clear what I mean.
Thanks in advance!!

**Comment by ionutvmi** [comment]
Hi @westr029 ,

Can you please ensure that the following preference is enabled ?

```
path-autocomplete.enableFolderTrailingSlash boolean - if true it will add a slash after the insertion of a folder path that will trigger the autocompletion.
```

**Comment by westr029** [comment]
Hmm, thanks. I just realized I mixed op your extension `path-autocomplete` with the extension `path-intellisense`.

After installing your extension it worked perfectly.

Thanks a lot!!
