### ISSUE TITLE
Enable file extensions for only certain filetypes

### ISSUE THREAD

**Issue by rameezk** [ionutvmi/path-autocomplete#35]
Hi there

Any easy way to do this? 

For example, enabled for *.scss files but not for *.js files. 

With transformations perhaps?

**Comment by ionutvmi** [comment]
You can do the reverse enable the extension for all the files and then apply transformations to remove the extensions from certain file types.

path-autocomplete.transformations List of custom transformation applied to the inserted text.
Example: replace _ with an empty string when selecting a SCSS partial file.
```
"path-autocomplete.transformations": [{
    "type": "replace",
    "parameters": ["^_", ""],
    "when": {
        "fileName": "\\.scss$"
    }
}],
```

Please let me know if this fixes your issue.

**Comment by rameezk** [comment]
Thanks, works great.
