### ISSUE TITLE
Question about path autocomplete working inside markdown

### ISSUE THREAD

**Issue by alanosman** [ionutvmi/path-autocomplete#36]
Hi there.

I love this tool, it's very helpful.  But I was wondering if there was any way to make it work with markdown so it supports this type of format:

`![](../images/releases/myimage.gif)`

Maybe it's in the configuration somewhere, but I couldn't find it.  

Also, when it does work from within quotes, and I am picking a file it does not seem to grab the extension of the file.  Is that a bug?

Thanks

**Comment by ionutvmi** [comment]
Hi,
The options are documented in this Readme section: https://github.com/ionutvmi/path-autocomplete#options

To make it work in markdown files you want to enable: `path-autocomplete.triggerOutsideStrings`
To include the file extension you should enable: `path-autocomplete.extensionOnImport`

Please let me know if this fixes your issues.

**Comment by alanosman** [comment]
@ionutvmi I totally missed those settings.  Sorry.  That works 100%.. thank you!
