### ISSUE TITLE
[Feature request] `extensionOnImport` for specific extensions only

### ISSUE THREAD

**Issue by ffxsam** [ionutvmi/path-autocomplete#39]
It would be great to set this so that certain file extensions would be added, but others would not. For example, I prefer to not have the extensions for `.js` files, but I do for `.vue` files. Maybe this option could be expanded to support the following syntax (with regex support):

```json
"path-autocomplete.extensionOnImport": {
  "js": false,
  "vue": true,
  "(gql|graphql)": true
}
```

Or maybe it makes more sense to have a default value that can be overridden:

```json
"path-autocomplete.extensionOnImport": {
  "default": true,
  "exceptions": {
    "js": false
  }
}
```

**Comment by ionutvmi** [comment]
I think it might be similar to the discussion we had on this ticket: https://github.com/ionutvmi/path-autocomplete/issues/35

Can you please try it out and check if it covers your use case ?

**Comment by ffxsam** [comment]
@ionutvmi Yep, that worked great, thanks!

```json
  "path-autocomplete.transformations": [
    {
      "type": "replace",
      "parameters": [
        "$",
        ".vue"
      ],
      "when": {
        "fileName": "\\.vue$"
      }
    }
  ]
```

**Comment by ionutvmi** [comment]
Awesome ! Closing this ticket.
