### ISSUE TITLE
[Enhancement] Add included items rules

### ISSUE THREAD

**Issue by DCKT** [ionutvmi/path-autocomplete#4]
Hi,

I think it could be great if we had the ability to add a specific folder to search.

Example : I'm using webpack with resolve module to the folder `src`, this gave me ability to avoid relative path and use absolute path from `src`.

What do you think ? Unfortunatly, I don't know TS so I'm unable to make a PR sorry 😔

**Comment by ionutvmi** [comment]
Basically to have the possibility to set the root folder when the path starts with `/` ?

**Comment by ionutvmi** [comment]
Starting with 1.3.0 you should be apple to this by using custom mappings

```
    "path-autocomplete.pathMappings": {
        "/": "${workspace}/src"
    }
```
