### ISSUE TITLE
Is it possible to choose slash type? 

### ISSUE THREAD

**Issue by u2berggeist** [ionutvmi/path-autocomplete#40]
It'd be nice to be able to chose slash type, or even some logic for where/when it should double up on backslashes (for example, the `settings.json` file requires the use of `\\` for Windows file paths).

**Comment by ionutvmi** [comment]
Starting with 1.12.0 you should be able to enable this behavior with `path-autocomplete.useBackslash`

Please try it out and let me know how this works.
