### ISSUE TITLE
Would you consider adding a branch to make this a Visual Studio Extension?

### ISSUE THREAD

**Issue by inunotaisho26** [ionutvmi/path-autocomplete#41]
I use Visual Studio community for Mac to run and test my .NET Core projects. Having this feature would be really useful. I would be willing to help and I know C#, which BTW is similar to Typescript.

**Comment by inunotaisho26** [comment]
@ionutvmi - started working on this for MacOS. https://github.com/inunotaisho26/path-autocomplete

**Comment by ionutvmi** [comment]
hi @inunotaisho26 ,

I'm happy to add a link in the readme once your extension is published.
You can create a PR with that change to the readme file once you consider it stable.
