### ISSUE TITLE
Adding paths without including the root folder

### ISSUE THREAD

**Issue by miinx** [ionutvmi/path-autocomplete#46]
Hi there,

I really like your plugin!  Thanks for your great work.

However, I have an issue I can't figure out, hoping you can help, please.

Our project structure has nested projects, something like:
```
- main project root folder
    - app
    - lib
    - test
    - nested project 1 root
       - src
       - test
    - nested project 2 root
       - src
       - test
```

I'd like to be able to insert paths from folders under the main project root, & subfolders of the nested projects -- but without including the relevant root folder.  

e.g.  I want to insert a path `selectors/someFile` (note no leading slash or dot) where `selectors` lives under `nested project 1 root/src`.

To do this, I've been trying to create multiple root folders (for main root & nested roots), but they seem need a name or something to trigger them:

```
"path-autocomplete.pathMappings": {
    "$root": "${workspace}/src",
    "/z": "${workspace}/nested1/src",
    "/w": "${workspace}/nested2/src"
}
```

with this I can type `/z/selectors/someFile` & it's auto-completed, however `/z/` remains.

I've tried using transformations to then remove the `/z/` but it doesn't work:

```
"path-autocomplete.transformations": [{
    "type": "replace",
    "parameters": ["\/z\/", ""]
}
```

The only other thing I can think of is to add explicit path mappings for every subfolder of each `src` -- but there are heaps of them, & we have duplicate folder names across projects, so I'd need to differentiate them somehow..  which all seems a bit hard.

Suspect I'm doing something wrong?  Any help appreciated, thank you!

Karen

**Comment by ionutvmi** [comment]
Path autocomplete provides information only from 1 folder at the time.
The transformations only apply to the newly inserted characters (file or folder name). That `/z` needs to remain in the path otherwise it won't be able to build the full path.

If I understand this correctly you are looking for is the possibility to combine multiple root folders ?
something like:
```
"$root": ["${workspace}/p1/src", ""${workspace}/p2/src""]
```
And then when you type `data/` it should search for the `data/` path in both `p1/src` and `p2/src`.
Is that correct ?

**Comment by ionutvmi** [comment]
Support for this has been added in 1.10.0.

Please try it out and let me know if it addressed your use case
