### ISSUE TITLE
it doesn't work with json files

### ISSUE THREAD

**Issue by FederAndInk** [ionutvmi/path-autocomplete#47]
## Behavior :
In *.json files
when we type '/' or './' between "quotes" the autocomplete isn't triggered
even if we do ctrl+space

it appears that when we type '.' outside a string the autocompletion suggest: ".." "." and hidden files
when we just trigger autocompletion it suggests all files and folders but it stops when a '/' is inserted

I have no other path completion plugins installed and it works perfectly in ts or scss files

![screenshot_20180529_110753](https://user-images.githubusercontent.com/24270152/40649393-1a75fefc-6331-11e8-9265-dc2ead28dea4.png)
![screenshot_20180529_110803](https://user-images.githubusercontent.com/24270152/40649395-1a92d2ac-6331-11e8-83e5-feab5b547d5d.png)
![screenshot_20180529_110821](https://user-images.githubusercontent.com/24270152/40649396-1aada424-6331-11e8-93e9-2d0b258359ac.png)
![screenshot_20180529_110835](https://user-images.githubusercontent.com/24270152/40649397-1ac7d510-6331-11e8-8bd4-38f875daa4af.png)
![screenshot_20180529_110842](https://user-images.githubusercontent.com/24270152/40649398-1ae64450-6331-11e8-8f57-3d127ba02385.png)

**Comment by joshua5822** [comment]
I am experiencing the same issue with yaml files.

**Comment by alpgul** [comment]
I'm having the same problem.

**Comment by Conceptron** [comment]
It's isn't working outside strings for me in markdown files after settings the option `path-autocomplete.triggerOutsideStrings` to `true`

**Comment by Conceptron** [comment]
Actually i checked again it was working in most cases, except when the characters \` come before: 
![output](https://user-images.githubusercontent.com/35289454/41585256-24a0ca3c-73c7-11e8-9dd9-dc0f5c4560b9.gif)

**Comment by ionutvmi** [comment]
I had a short look today over this but I couldn't find a solution.  
We are sending the completionItems but they are not displayed by vscode.  
I will keep this ticket open until we find a solution (any suggestions or PRs are welcomed here).

@Conceptron can you open a separate issue to discuss that use case ?
Currently it uses quotes to determine the start of the path and it is the reason why you are getting no suggestion when you have `'` or `` ` `` on the same line.

**Comment by mhamri** [comment]
+1

**Comment by atomheart** [comment]
Still not working.

**Comment by ionutvmi** [comment]
This should be fixed in path-autocomplete@1.13.3

Please try it and let me know if this is resolved.
