### ISSUE TITLE
multiple suggesion in js files

### ISSUE THREAD

**Issue by cannap** [ionutvmi/path-autocomplete#48]
Hi, nice extension i helps me alot in vue files :D but in js files i get multiple suggestions
https://www.useloom.com/share/25c4c6e4e67140aabe8b5fceb5639acc 

is there a way to disable it for JS files?

**Comment by ionutvmi** [comment]
As far as I can tell the suggestions get merged with the native vscode suggestions.  

As a solution here you can try to disable the native suggestion:
```
"typescript.quickSuggestionsForPaths": false
```

Please re-open this ticket if this doesn't fix your issues.
