### ISSUE TITLE
Stops working if there are spaces in the folder names

### ISSUE THREAD

**Issue by Arwalk** [ionutvmi/path-autocomplete#49]
As explicit as the title says. I was trying to do relative-path m3u playlists by hand using this extension, but noticed that as soon as the folder name had a space in it, the autocomplete failed to get the filenames inside the folder.

Here's an example:

Step 1: "Synkronized" is a one word album name, so i select it...
![capture d ecran 2018-07-11 23 31 55](https://user-images.githubusercontent.com/4776412/42600658-71c356ba-8563-11e8-9d8a-a9c2799fcf83.png)

Step 2: The extension finds the titles in the folder
![capture d ecran 2018-07-11 23 32 01](https://user-images.githubusercontent.com/4776412/42600660-74a92738-8563-11e8-917f-3fbc949d6224.png)

Step 3: "Emergency on Planet Earth" contains some spaces
![capture d ecran 2018-07-11 23 32 06](https://user-images.githubusercontent.com/4776412/42600664-7686aa80-8563-11e8-9f50-566be35b1e2c.png)

Step 4: The extension fails to find any file in the folder
![capture d ecran 2018-07-11 23 32 12](https://user-images.githubusercontent.com/4776412/42600667-79d534fe-8563-11e8-98cb-9ea26cdae442.png)

OS: Windows 10
VSCode version: 1.24.0
Extension Version: 1.10.0

**Comment by ionutvmi** [comment]
Can you try to temporarily add quotes and then remove them one you completed the full path ?
```
"/folder/
```

The way it works at the moment is that it tries to find the previous quote character and if none if found it uses the previous space.
I will check in the weekend to see if I can move that logic in some configurations.

**Comment by Arwalk** [comment]
This indeed seems to be a decent workaround. Thanks for the support.

**Comment by ionutvmi** [comment]
In 1.11.0 a new option has been introduced.
You can use `path-autocomplete.includeExtension` to cover your use case.

Example:

```
path-autocomplete.includeExtension: "({["
```
