### ISSUE TITLE
Problems when adding ?-parameters to file path 

### ISSUE THREAD

**Issue by kasvtv** [ionutvmi/path-autocomplete#52]
So some loaders accept specific parameters for each import, such as:

`import image from './img/image.jpg?placeholder=true';
`

Since the plugin (rightfully so) interprets this as part of path, it is seen as incorrect, so I tried to make a regex to replace everything starting from question mark until the end of the string with nothing:

```
    "path-autocomplete.transformations": [{
        "type": "regex",
        "parameters": ["\\?.+$", ""],
        "when": {
            "fileName": "**"
        }
    }]    
```

Couldn't get it to work though... What did I do wrong? Must be a simple fix

**Comment by kasvtv** [comment]
Hello, thanks for the quick answer, much appreciated.

Yes this is something that I add manually. The file would just be called image.jpg in case of the example I gave above. Actually, passing parameters this way is part of the Webpack specification for file loaders:

https://webpack.js.org/concepts/loaders/#inline

Would there be any way for the plugin to be able to account for me adding a parameter this way? If not, would there be any objections to make this plugin comply with the Webpack loader spec?

I would love to continue using it together with import parameters without having it give me these errors. I think it might be a good addition, since Webpack is one of the most widely used ways to resolve JS imports, so others using both this plugin and Webpack

**Comment by kasvtv** [comment]
Misclicked on my phone and accidentally closed the issue.

**Comment by ionutvmi** [comment]
What kind of errors do you get ?
As far as I understand once you add `?placeholder=true` the path is complete so there is nothing that path-autocomplete can help with after that,
The suggestions are only triggered after you type the `/` character.

To understand the situation better maybe you can add the steps that you are performing, a screenshot and an Expected result/Actual result

**Comment by ionutvmi** [comment]
Closing this for now.
Please reopen if you have more details and this is still and issue.
