### ISSUE TITLE
Files with custom extensions not listed for import

### ISSUE THREAD

**Issue by Jaans** [ionutvmi/path-autocomplete#53]
How do I configure the file extensions that are considered during path intellisense?

**Comment by ionutvmi** [comment]
there is no filtering on the results.
You should be able to see all the files that are available in the folder.

Can you please provide a screenshot/example folder structure where you are seeing the issue ?

**Comment by Jaans** [comment]
Thank you for your quick reply. I think I've narrowed the issue down a bit.

If the path I'm looking at has no subfolders, it works perfectly:
![image](https://user-images.githubusercontent.com/3510981/43673729-12092f96-980b-11e8-8c60-f80602a50671.png)

However, if the path has a subfolder (irrespective of whether that folder contains anything) it doesn't work and only lists the subfolder itself:
![image](https://user-images.githubusercontent.com/3510981/43673741-4b964f0a-980b-11e8-9b30-17dc421f9e98.png)

Does that help?

**Comment by ionutvmi** [comment]
Can you try to go to User settings and disable the typescript path suggestions ?

```
    "typescript.quickSuggestionsForPaths": false
```

**Comment by Jaans** [comment]
Unfortunately disabling that setting did not work. I closed VSCode to make sure, but it doesn't seem to make any different. 

Is this an issue that's only happening to me / my environment or is this for all users?

**Comment by ionutvmi** [comment]
Hi @Jaans ,

Can you please let me know if this is still an issue with the latest version 1.13.3 ?
I was not able to reproduce it

**Comment by Jaans** [comment]
It seems to be working lately so happy to close issue.
Thanks for following up.
