### ISSUE TITLE
Folders are duplicated on sass import statement

### ISSUE THREAD

**Issue by LukasPolak** [ionutvmi/path-autocomplete#56]
Hi!
I have a problem with duplicated folders on sass (scss) file types.
When the extension is disabled, everything looks fine
![disabled](https://user-images.githubusercontent.com/17145302/48188773-d4a71f80-e33e-11e8-870b-1dde61b87df4.png)

But when I enable the extension, folders are duplicated.
![enabled](https://user-images.githubusercontent.com/17145302/48188823-ee486700-e33e-11e8-85db-5ec6a9890129.png)

I have disabled javascript and typescript path suggestion with:
```
"javascript.suggest.paths": false,
"typescript.suggest.paths": false,
```
But I have didn't find a setting for sass (scss). Do you know some settings for that,
or can you provide an option to disable this extension on selected file types?

Thanks a lot

**Comment by hukoutuoxian** [comment]
me too !

**Comment by gnimor** [comment]
Also here

**Comment by ionutvmi** [comment]
I had a quick look here and didn't found any option to disable the css language server path completions.

As a result starting with 1.13.0 the option `path-autocomplete.ignoredFilesPattern` has been introduced.
You can find more details about it in the readme file.

Please confirm that this options fixes the issue on your side.

**Comment by LukasPolak** [comment]
Yes, it is fixed now. Thanks
