### ISSUE TITLE
Single backslash

### ISSUE THREAD

**Issue by ukandrewc** [ionutvmi/path-autocomplete#57]
Can you add an option to only use a single backslash during insertion.
I just need \path\ not \\\path\\\

Thanks

**Comment by ionutvmi** [comment]
Can you please provide an use case for it ?

The way we have it right now it will insert `\\` if you are in a quoted string, otherwise it will insert `\`

**Comment by smandon** [comment]
I second this.

A use case: windows bat files which do not require escaping in quoted string.

**Comment by byehack** [comment]
Another bug maker situation is when we are in raw-string-literal.
raw strings already ignores escape character, so we don't need to use double backslash!
![image](https://user-images.githubusercontent.com/26390254/187531924-e48b8118-f5c3-4854-961d-17be524fd136.png)

**Comment by ionutvmi** [comment]
this has been fixed in v1.21.0
Please try it out and reopen if you notice any issues.

the `path-autocomplete.useSingleBackslash` preference has been introduced to control this.

I also tried to add some detection for that raw-string-literal use case listed above.
