### ISSUE TITLE
Keyboard navigation stopped working recently

### ISSUE THREAD

**Issue by anishmittal2020** [ionutvmi/path-autocomplete#59]
Example: I want to type path `./Sync/Hello.pdf`. 

**Previously**, I could select Sync from drop down menu by navigating to it and pressing enter and then  it used to show me all files inside Sync folder in a drop down menu, from which Hello.pdf could be selected by pressing enter (I didn't need to use mouse at all).

**Now**, if I press enter as above nothing gets printed and the drop down list goes away. It works only if I use mouse to click (instead of enter).

Please resolve this issue.

**Comment by ionutvmi** [comment]
Hi @anishmittal2020 ,

I am not able to reproduce this issue.
Is this issue still valid with the most recent version of vscode and the extension ?

**Comment by ionutvmi** [comment]
Closing this for now.
Please reopen this if you still encounter issues.
