### ISSUE TITLE
Another folder path issue

### ISSUE THREAD

**Issue by rhernandog** [ionutvmi/path-autocomplete#6]
Hi,

Nice work creating the update and solving the previous issue!!

Unfortunately I have a new one. Turns out that when a folder has periods and a number as the final character, the final period and the number(s) after it are not included.

What should look like this:
`/scripts/gsap/1.19.0/`
Actually looks like this:
`/scripts/gsap/1.19/`

Regardless if the folder is selected with the mouse or keyboard.

**Comment by ionutvmi** [comment]
This should be fixed in 1.2.1
