### ISSUE TITLE
Path Suggestions have duplicates and errors

### ISSUE THREAD

**Issue by liby** [ionutvmi/path-autocomplete#61]
- Configuration Information
  - Windows 10 X64 Enterprise Edition

- VScode version
  - 1.33.0

- Problem Description
  - Each suggestion item is repeated twice.
  - Irrelevant Suggestions will appea.

- The problem record the screen
![demo](https://user-images.githubusercontent.com/38807139/55858512-7490ff80-5ba2-11e9-8fe0-8dab492d4294.gif)

**Comment by ihodev** [comment]
In `.js` & `.ts` files duplicates come from

```json
"typescript.suggest.paths": true,
"javascript.suggest.paths": true,
```

Any chance to filter them out without setting `false`, because these settings also provide autocomplete for `node_modules`.

**Comment by liby** [comment]
@ihodev 
After changing the configuration, the problem persists

**Comment by COD3BREAK3R** [comment]
My problem is the same in HTML files, you should add an easy option to understand and configure in which you can disable the suggestions in different types of files, I tried to do it by the documentation that brings the extension but I could not.

**Comment by ionutvmi** [comment]
@COD3BREAK3R have you tried the `ignoredFilesPattern` option ?

```
    "path-autocomplete.ignoredFilesPattern": "**/*.{css,scss,html}",
```

**Comment by liby** [comment]
@ionutvmi 
- This setting does solve the problem of suggesting duplicates.
![demo](https://user-images.githubusercontent.com/38807139/60593985-89161a00-9dd6-11e9-8b01-e5213b62062f.gif)
### Would you like to say something different about your plugin and the plugin below?
  - I see that the functions of these two plugins are highly similar.
  - Do I need to use them at the same time?
[PathIntellisense](https://github.com/ChristianKohler/PathIntellisense)

### Finally, ask if your plugin doesn't seem to work in the vue file.

**Comment by ionutvmi** [comment]
@liby , path intellisense was the starting point for this extension.
Since they are doing the same thing (providing path competitions you should only use one at a time.

For the vue file issue can you please open a new issue with more details on how to reproduce ?

**Comment by ionutvmi** [comment]
```
 "path-autocomplete.ignoredFilesPattern": "**/*.{css,scss,html}",
```

For now the recommended solution for handling duplicates would be to disable path autocomplete based on the extensions where vscode provides completions out of the box.

**Comment by COD3BREAK3R** [comment]
> @COD3BREAK3R have you tried the `ignoredFilesPattern` option ?
> 
> ```
>     "path-autocomplete.ignoredFilesPattern": "**/*.{css,scss,html}",
> ```

I tried to do it, but it did not work, I did not understand very well how it was put. I read the Readme again and again but I could not, I'm going to try your configuration to see if it works, thanks.

**Comment by ionutvmi** [comment]
@COD3BREAK3R , in that list you can add file types where you don't want path autocomplete to provide suggestions.
`css,scss,html}` means that it will not provide suggestions in css, scss and html files.

On what type of files are you working on ?

**Comment by COD3BREAK3R** [comment]
> @COD3BREAK3R , in that list you can add file types where you don't want path autocomplete to provide suggestions.
> `css,scss,html}` means that it will not provide suggestions in css, scss and html files.
> 
> If that doesn't work please open a new issue with more details.
> Include the file type you are working on and the configuration that you tried.

I already tried the configuration and it worked, this should be implicit in the documentation and if you can add it already by default in an update it would be great.
