### ISSUE TITLE
Increase Popup Size - Aumentar tamanho do popup

### ISSUE THREAD

**Issue by eltonlimaribeiro** [ionutvmi/path-autocomplete#62]
Would you like to increase the size of the suggestion window? So I could see the full name of the file.
In Brackets this window is much larger

Teria como aumentar o tamanho da janela de sugestões? Assim poderia ver o nome completo do arquivo.
No Brackets essa janela é bem maior

![vccode](https://user-images.githubusercontent.com/46497964/57930852-64e59480-788d-11e9-98cc-1b3f0609d1ec.jpg)

**Comment by tjx666** [comment]
You can just drag the region to resize popup size:

![image](https://user-images.githubusercontent.com/41773861/153384171-55762b00-0f63-40a1-aa9b-b170cb5dd189.png)
