### ISSUE TITLE
Problem with duplicate folders

### ISSUE THREAD

**Issue by kanlukasz** [ionutvmi/path-autocomplete#67]
Hello,

I have a problem with folders duplicates in suggestions
As in the picture below:

![obraz](https://user-images.githubusercontent.com/30685349/71969456-fb910800-3206-11ea-99d3-dce04981b28d.png)

Can you tell me why this is happening? Can anything be done about it?

Tested on:
```
Version: 1.42.0-insider
Commit: cba31b819ea99836daf51cee56299348e9c6d20b
Date: 2020-01-08T05:39:25.874Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by ionutvmi** [comment]
On some file types vscode also provides suggestions for path autocompletions.
To avoid duplicates you can use the `path-autocomplete.ignoredFilesPattern` to disable path autocomplete on those file types.

You can also review the discussions here:
https://github.com/ionutvmi/path-autocomplete/issues/61
https://github.com/ionutvmi/path-autocomplete/issues/56
