### ISSUE TITLE
File extension not inserted for files

### ISSUE THREAD

**Issue by drkarthi** [ionutvmi/path-autocomplete#68]
The filename comes with the extension in the suggestions, but does not get populated with the extension:
![image](https://user-images.githubusercontent.com/6463520/72568804-8fee1100-387e-11ea-9876-4e35eab3d212.png)
![image](https://user-images.githubusercontent.com/6463520/72568813-95e3f200-387e-11ea-996a-4657947a4cb4.png)

I came across the path-autocomplete.includeExtension setting in the documentation, but I do not see or add this setting:
![image](https://user-images.githubusercontent.com/6463520/72568966-e1969b80-387e-11ea-8463-ff5e5743e59d.png)

**Comment by ionutvmi** [comment]
i just checked and the option shows up.
were you on the srable version of vscode at the time ?

**Comment by tjx666** [comment]
Can't reproduce.
