### ISSUE TITLE
path-autocomplete.excludedItems doesn't work

### ISSUE THREAD

**Issue by gmccullo** [ionutvmi/path-autocomplete#69]
Either it doesn't work or I'm not using it correctly. Here's my setting:
```
	"path-autocomplete.excludedItems": {
		"**/*.js": {
			"when": "**/*.txt"
		}, // ignore js files if i'm inside a txt file
		"**/*.css": {
			"when": "**/*.txt"
		}, // ignore css files if i'm inside a txt file
	},
```
But here's what I see:

![image](https://user-images.githubusercontent.com/26315643/73338090-1d196880-4276-11ea-86f9-eef525a1bb1a.png)

I don't expect to see JS files in the list.

**Comment by ionutvmi** [comment]
those completions items are generated directly by vscode

you can try searching in the standard settings if there is any way to disable them

**Comment by gmccullo** [comment]
Sorry, I don't understand. If the completions are generated by vscode, what's the Path-Autocomplete extension for?

**Comment by ionutvmi** [comment]
when the extension was first created back in 2016 vscode didn't have that completion functionality for paths.
Additionally it doesn't provide as much flexibility for modifying the path, choosing if you need the extension or not.

Please review it again and if everything is good you can close this issue.

**Comment by gmccullo** [comment]
Thanks. The native functionality is good enough for me. You can close the issue.
