### ISSUE TITLE
Missing extension

### ISSUE THREAD

**Issue by rhernandog** [ionutvmi/path-autocomplete#7]
Hi, me again :stuck_out_tongue_closed_eyes: 

After the fix from #6, the extensions are not included in the files, instead of:
`/scripts/gsap/1.19.0/TweenMax.js`
It returns:
`/scripts/gsap/1.19.0/TweenMax`

**Comment by nazarex** [comment]
Returns without extension
js/default.js
It returns:
js/default

on Ubuntu 16.04

**Comment by ionutvmi** [comment]
Try adding this into your user settings

```
  "path-autocomplete.extensionOnImport": true,
```

**Comment by nazarex** [comment]
Qapla!!!  Adding the line: "path-autocomplete.extensionOnImport": true

File>Preferences>User Settings
Worked. 

Thank you. This extension is very helpful.

**Comment by ionutvmi** [comment]
Awesome !
I will close this issue since this is resolved.
