### ISSUE TITLE
SCSS - Autocomplete relative to compiled file and not source

### ISSUE THREAD

**Issue by paulmist** [ionutvmi/path-autocomplete#71]
I'd love to be able to autocomplete paths relative to the compiled CSS file rather than my source SCSS file.

Eg. The source is in `src/scss/source.scss` and compiles to `src/style.css`

**Comment by ionutvmi** [comment]
You can try to play around with the transformations feature

Assuming that all the files from `src/scss/*` point to `src/style.css` you could try something like thisL

```
"path-autocomplete.transformations": [{
    "type": "replace",
    "parameters": ["src/scss/.*", "src/style.css"],
    "when": {
        "fileName": "\\.scss$"
    }
}],
```

Please try it out and close the ticket if this works.

**Comment by paulmist** [comment]
Thanks, @ionutvmi.

No luck thought I'm afraid - the autocomplete choices displayed in the UI are still always relative to the current document and not the compiled/destination document.

**Comment by ionutvmi** [comment]
Hi @paulmist ,

You can try having a look at the `"path-autocomplete.pathMappings": {` for that use case.

**Comment by paulmist** [comment]
Ok - working with

```
"path-autocomplete.pathMappings": {
        "img": "${folder}/img"
    }
```
