### ISSUE TITLE
How to autocomplete from empty string?

### ISSUE THREAD

**Issue by philipshen** [ionutvmi/path-autocomplete#75]
I use absolute imports in my project––for example to import `/src/utils/example.js` I will write `import example from 'utils/example'`. However I can't seem to get autocomplete working from an empty string. This code from the examples works the way it should:

```
"path-autocomplete.pathMappings": {
        "/": "${folder}/src"
 },
```

However using an empty string instead of a slash doesn't. Is there any way to get this working?

**Comment by tjx666** [comment]
I don't think we would add this feature. In your use case, you would better just type 'u' to get suggestion from VSCode builtin support.

![image](https://user-images.githubusercontent.com/41773861/153385972-a68c2202-8f13-49e4-82c1-a1320840eba6.png)
