### ISSUE TITLE
Feature request: Support absolute path import with "baseUrl" setting

### ISSUE THREAD

**Issue by midoriki** [ionutvmi/path-autocomplete#77]
Firstly thank you very much for this extension, I have searched for days to find one to help me import css/scss file with suggestions in React code, finally found this one.

I have a feature request is that currently this extension only supported absolute path import to the workspace (starting with /), can you add support for absolute path import base on "baseUrl" setting in jsconfig.json/tsconfig.json ?

Thank you very much.

**Comment by ionutvmi** [comment]
Hi @midoriki ,

have you tried to configure the `pathMappings` ?

```
"path-autocomplete.pathMappings": {
    "/test": "${folder}/src/Actions/test", // alias for /test
    "/": "${folder}/src", // the absolute root folder is now /src,
    "$root": ${folder}/src // the relative root folder is now /src
    // or multiple folders for one mapping
    "$root": ["${folder}/p1/src", "${folder}/p2/src"] // the root is now relative to both p1/src and p2/src
}
```

https://github.com/ionutvmi/path-autocomplete#options

**Comment by midoriki** [comment]
Hi @ionutvmi,

Thank you for your suggestions, it worked really well.

FYI, for anyone run into this problem like me:

I'm working on 2 projects: the first is a next.js project where source files are in the project's root directory, and the other is a CRA project where source files are in src directory. You can set it up like this and you can use absolute path import file that isn't JS/TS in both projects.

```
"path-autocomplete.pathMappings": {
    "$root": ["${folder}", "${folder}/src"]
}
```

**Comment by ionutvmi** [comment]
glad it helped
