### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by techwithsam** [ionutvmi/path-autocomplete#78]
- Issue Type: `Performance`
- Extension Name: `path-autocomplete`
- Extension Version: `1.13.6`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.45.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\OBOUNCE\ionutvmi.path-autocomplete-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ionutvmi** [comment]
Hi @acctgen1 ,

Can you please provide more details about the folder structure that you had ?
Was it something that had a very large amount of files in it ?

**Comment by tjx666** [comment]
close because no response.
