### ISSUE TITLE
Thanks your  ,There was show  two files  how to fix it. 

### ISSUE THREAD

**Issue by Rice888** [ionutvmi/path-autocomplete#80]
<img width="674" alt="截屏2020-06-26 下午5 52 48" src="https://user-images.githubusercontent.com/59442434/85844858-f8e69700-b7d5-11ea-8879-ea27a29e504e.png">

**Comment by ionutvmi** [comment]
Can you try the solution from this ticket:  https://github.com/ionutvmi/path-autocomplete/issues/70 ?
