### ISSUE TITLE
Inhibit on double slash

### ISSUE THREAD

**Issue by Gruntfuggly** [ionutvmi/path-autocomplete#81]
Great extension - I use it every day, but I have a tiny issue.

The extension starts autocompleting when I enter comments, e.g. `//`. Sometimes I just want to stick a comment at the end of a line, but the extension inserts the completion when I press enter (which I would expect).

I know this is actually a valid path, but in practice I don't think it would be used or expected to be completed?

I use clang-format to automatically insert ending namespace comments, and this breaks that.

**Comment by ionutvmi** [comment]
Upgrade to 1.14.0 and configure the following in your setting

```
 "path-autocomplete.ignoredPrefixes": [
        "//" // type double slash and no suggesstions will be displayed
    ]
```

Please reopen the ticket if you still encounter issues.

**Comment by Gruntfuggly** [comment]
Thanks! I'll try it at work tomorrow and let you know.

**Comment by Gruntfuggly** [comment]
Work a treat - thanks!
