### ISSUE TITLE
Is it supposed to work with python?

### ISSUE THREAD

**Issue by mostafahadian** [ionutvmi/path-autocomplete#82]
It doesn't work with python.

**Comment by ionutvmi** [comment]
Hi @mostafahadian ,

Can you provide an example of a code snippet where you tried to use it ?

**Comment by mostafahadian** [comment]
Hi,

I have enabled autocomplete.triggerOutsideStrings but still it doesn't work anywhere:
- in stringss
- ouside strings
- in .py files
- even in .js files

**Comment by ionutvmi** [comment]
hi @mostafahadian ,

It seems to work for me it's just that they are added at the end of the list, so it might that be that obvious that they are there

![image](https://user-images.githubusercontent.com/3531898/87409775-1be2ba80-c5ce-11ea-973f-7b35eefbe4e3.png)

**Comment by mostafahadian** [comment]
Hi @ionutvmi ,

Yes I checked it and it works perfectly.
Also I think It would be nicer if there were an option to list the directories at the beginning of the suggestions list.

Thanks a lot.
