### ISSUE TITLE
Disabling suggestion on folders

### ISSUE THREAD

**Issue by ekr3peeK** [ionutvmi/path-autocomplete#83]
Is it possible somehow, to disable folder suggestions altogether? The reason for this are duplicate folders are being shown. The other proposed solution I found in the closed issues, won't do for me, as I need to have the native suggestions enabled also.

**Comment by ionutvmi** [comment]
Leaving some notes here for the near future when I will find some time to work on this.

My current idea is to extend the capabilities of the excludeItems options with something like follows:

```
"path-autocomplete.excludedItems": {
         "**": { "when": "**", "isDir": true }, // always ignore `folder` suggestions
         "**/*.js": { "when": "**", "context": "import.*" }, // ignore .js file suggestions in all files when the current line matches the regex from the `context`
}
```

This additional logic will need to be added in the filter method from the completion provider:
https://github.com/ionutvmi/path-autocomplete/blob/master/src/features/PathAutocompleteProvider.ts#L458

**Comment by ionutvmi** [comment]
This is now included in 1.15.0 

Please try it out and let me know if worked for you.

**Comment by ekr3peeK** [comment]
Works as a charm, nice, Thanks!:)

I would have an additional suggestion also. It would be nice, if it would be possible to provide custom mappings that resolve to certain file types only.

My problem is the following: at the moment, when working with SCSS you are not able to define custom folder aliases on import, thus neither VS code, nor the SCSS Intellisense that I found for VS Code supports this feature. However, when bundling my project using either `webpack` or `browserify`, both provide a way to define custom folder aliases in `scss` also. Thus, it would be nice, if I would be able to provide a custom mapping and use `path-autocomplete` for import suggestions.

Why I would need this functionality is that, right now, I am aliasing my folders in typescript with `core` for the in-house made framework we are using, and `project`, for the current project that extends this framework. I would like to do the same with scss also, as our in-house made framework has scss files also, but they are stored in a completely different directory, thus I can not alias two separate `core` directories. 

If I could specify that when I am in an `.scss` file, `core` referes to A, and when I am in a `.ts` file, `core` refers to B would be really helpful. In the meanwhile, I know that I could just rename those aliases to `coreSCSS` and `coreTS`, but if this feature wouldn't be too hard to implement, I think others would benefit from it also!

**Comment by ekr3peeK** [comment]
Another question. Is it possible somehow, to also map file openings with this extension? For example, could it be made, that when I click on the link part of the import statement, VS code should use the mappings of `path-autocomplete` to open the file?
