### ISSUE TITLE
Absolutely path autocomplete not working on HPC

### ISSUE THREAD

**Issue by Zepeng-Mu** [ionutvmi/path-autocomplete#84]
Hi, thanks for this great extension.
I am using VS code on our computing cluster and since I cannot root so I installed VS code in my home folder.
I found that auto-completion for relative path works fine, but it is not working for absolute paths starting with "/".
I am wondering whether this is because I do not have root privilege and if there's any way to solve this.
Thank you so much!

**Comment by ionutvmi** [comment]
It might be a permissions issues.
Unfortunately I don't have an environment like that to test it on.

If you try to start from the current folder with a relative path: `./../../../` how high can you go in the folder structure.
Additionally you might want to have a look at the `"path-autocomplete.pathMappings": {` configuration if you need to map the root `/` to another folder.

**Comment by Zepeng-Mu** [comment]
Yes indeed using relative path I can go to `/`. I will try using pathMapping. Thank you!

**Comment by floriandeboissieu** [comment]
I had a similar experience on Ubuntu 22.04 (without permission issue): 
- starting with '/' does not autocompleted to root but to $HOME directory
- starting with '/home' --> no suggestion

In order to make it work correctly with absolute paths, I had to add the following in settings.json:
```
    "path-autocomplete.pathMappings": {
        "/":"/"
    }
```
