### ISSUE TITLE
How can I prevent duplicates?

### ISSUE THREAD

**Issue by homestar9** [ionutvmi/path-autocomplete#86]
For some reason, the autocomplete plugin always shows the contents of the directory twice.  In the notes section of the documentation, it says _"if you have issues with duplicate suggestions please use the `path-autocomplete.ignoredFilesPatter` option to disable the path autocomplete in certain file types"_  However, I do not want to disable certain file types, I just want to eliminate duplicate files or folders from the list of suggestions.

How can I use `path-autocomplete.ignoredFilesPattern` to ignore duplicates?  It's also interesting that the duplicates are not always right next to each other. It is not clear what sorting method is used when listing possible matches.

![duplicates](https://user-images.githubusercontent.com/5341142/94295601-504fec80-ff16-11ea-8a9a-53032a9ffc2b.gif)

**Comment by ionutvmi** [comment]
Try with the `excludedItems` option, it allows you control based on the current line context.

```
// disable all suggestions in HTML files, when the current line contains the href or src attributes
"path-autocomplete.excludedItems": {
        "**": {
            "when": "**/*.html",
            "context": "(src|href)=.*"
        }
},
```

Please try it out and close the issue if it works for you.

**Comment by ionutvmi** [comment]
Related to #85

**Comment by homestar9** [comment]
That did the trick! Thank you.
