### ISSUE TITLE
Suggestion while typing

### ISSUE THREAD

**Issue by shhlkien** [ionutvmi/path-autocomplete#87]
It doesn't trigger suggestions while typing.
If I press `ctrl + space` before typing any word, it will pop up a list of paths
![image](https://user-images.githubusercontent.com/23404165/94933171-3c971e00-04f4-11eb-8fc9-39eca6769d23.png)
But if I type something then press `ctrl + space`, it doesn't show anything
![image](https://user-images.githubusercontent.com/23404165/94933308-6b14f900-04f4-11eb-9d7c-89519f03032c.png)
Seem it's a bug

**Comment by ionutvmi** [comment]
Support for this has been added in version 1.17.0
Can you please try it out and let me know if it works for you ?

**Comment by shhlkien** [comment]
Yes, it works. Thank you so much
