### ISSUE TITLE
Duplicate paths or no npm modules autocomplete.

### ISSUE THREAD

**Issue by BatiuszkaMaroz** [ionutvmi/path-autocomplete#88]
My problem is I got duplicate paths while using this extension. Setting { typescript.suggest.paths: false } solves this problem but then I'm not getting any suggestions about installed npm modules. How to solve this problem?

**Comment by ionutvmi** [comment]
Can you try some of these solutions:

https://github.com/ionutvmi/path-autocomplete/issues/85
https://github.com/ionutvmi/path-autocomplete/issues/86

If they work for you please confirm and close this issue.

Have a nice day !
