### ISSUE TITLE
Duplicate path and file, when in .vue file.

### ISSUE THREAD

**Issue by JJLau626** [ionutvmi/path-autocomplete#91]
Such as this pic , I found suggestion didn't work  in .vue file , but .js or .ts file  are work.

In .vue file
![微信截图_20210128143037](https://user-images.githubusercontent.com/26458821/106100226-f175da80-6176-11eb-8836-0efdb307ebd0.png)

In .js file
![微信截图_20210128143221](https://user-images.githubusercontent.com/26458821/106100289-0b172200-6177-11eb-88d6-342be741fb4e.png)

**Comment by ionutvmi** [comment]
Try to configure the `path-autocomplete.excludedItems`

if you need more fine grained control for handing duplicate items you can use the path-autocomplete.excludedItems option as follows:
```
// disable all suggestions in HTML files, when the current line contains the href or src attributes
"path-autocomplete.excludedItems": {
        "**": {
            "when": "**/*.html",
            "context": "(src|href)=.*"
        }
},

// for js and typescript you can disable the vscode suggestions using the following options
"javascript.suggest.paths": false,
"typescript.suggest.paths": false
```

**Comment by ionutvmi** [comment]
please reopen if you still encounter issues
