### ISSUE TITLE
Absolute path to workspace with backslash is not working

### ISSUE THREAD

**Issue by beasthunter97** [ionutvmi/path-autocomplete#95]
I'm using VSC on windows. When I use `\` and `.\`, the extension only suggest relative files and folders

**Comment by ionutvmi** [comment]
Can you please share the configurations that you have for the `"path-autocomplete.pathMappings"` ?

**Comment by beasthunter97** [comment]
I don't have any configure for anything. I've just tried it out

**Comment by ionutvmi** [comment]
You should be able to change the location of the absolute path as follows:

To setup the root at disk root
```
    "path-autocomplete.pathMappings": {
        "$root": "/"
    },
```

To setup the root as the current workspace:
```
    "path-autocomplete.pathMappings": {
        "$root": "${workspace}/"
    },
```

Please close the issue if this works for you.

**Comment by beasthunter97** [comment]
Thank you, that worked
