### ISSUE TITLE
Doesn't work sometimes.

### ISSUE THREAD

**Issue by d0ob** [ionutvmi/path-autocomplete#99]
Hi there !

It sometimes doesn't work, but I don't see what's the difference with when it works.
Example: "Program file" is fine, but "program file (x86)" stop the autocomplete there.

I see that sometimes the autocomplete show me folder that I don't have, it also show some in another name than their real name. Seems like it's their english name while my windows/explorer is in french, could it be related to the issue ? ( In the explorer, that "program file" path is "programmes" for exemple. But strangly enought it still works though ! While Program File (x86) doesn't but that's the right name ^^ )

So I'm a bit lost about why it happens ! Any idea ? What should I do ? 
I've read the readme and look in the github, but didn't found anything related, maybe I missed it.. 
_( I also hugely edited my issue because I was testing it along side doing it, I shouldn't have =/ Sorry about that. Also, some issue were totally on my stupid side... ^^ )_

**Comment by ionutvmi** [comment]
it may stop working if you are trying to access folder where administartor/special permissions are needed to read that folder.

In order to get path completions for those folder you need to start VSCode as a use that can read those folders.
